# Streamlit Secrets Configuration
# IMPORTANT: Never commit this file to version control!
# This is an example file - in production, this file should be added to .gitignore

[api_keys]
# OpenAI API configuration
openai_api_key = "sk-example-key-replace-with-actual-key"
openai_org_id = ""

# Claude/Anthropic API configuration
anthropic_api_key = "sk-ant-example-key-replace-with-actual-key"

# Other API keys
google_api_key = ""
serper_api_key = ""

[database]
# Database connection information
connection_string = "sqlite:///./data/forecast_costs.db"
username = ""
password = ""

[services]
# External service configurations
error_reporting = false
monitoring_endpoint = "https://monitoring.example.com/api/health"
sentry_dsn = ""
cloudwatch_group = "forecasting-tools"
cloudwatch_stream = "application-logs"

[features]
# Feature flags for controlling functionality
enable_web_search = true
enable_research_tools = true
enable_benchmark_tools = false
enable_health_check = true
enable_error_reporting = false

[deployment]
# Deployment-specific configuration
environment = "development"  # development, staging, production
log_level = "INFO"
max_history_size = 100

[error_handling]
# Error handling configuration
show_error_details = true  # Show detailed errors in development
retry_api_calls = true     # Automatically retry failed API calls
max_retries = 3            # Maximum number of retries for API calls
enable_error_boundaries = true  # Use error boundaries for components 